services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: rag-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: rag-ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  ollama-model-loader:
    image: ollama/ollama
    container_name: rag-ollama-model-loader

    depends_on:
      ollama:
        condition: service_healthy

    environment:
      OLLAMA_HOST: http://ollama:11434

    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ollama pull bge-m3
        ollama pull qwen3:8b
        ollama pull gemma3:12b
        ollama pull deepseek-r1:8b
        ollama pull qwen3:14b
        ollama pull mistral-small3.2:24b

volumes:
  postgres_data:
  ollama_data:
